apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example2-stg
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: karol
spec:
  project: default
  destination:
    name: in-cluster
    namespace: stg
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/bakunowski/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
